# Generated by Django 4.1.4 on 2023-02-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NhlPreds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        default="2023-02-06", max_length=64, verbose_name="Date"
                    ),
                ),
                ("skater", models.CharField(max_length=64, verbose_name="Skater")),
                ("team", models.CharField(max_length=3, verbose_name="Team")),
                ("opponent", models.CharField(max_length=3, verbose_name="Opponent")),
                ("prediction", models.FloatField(verbose_name="Prediction")),
            ],
        ),
    ]
