# Generated by Django 4.1.4 on 2023-01-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nhl", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nhlpreds",
            name="date",
            field=models.CharField(
                default="2023-01-23", max_length=64, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="nhlpreds",
            name="id",
            field=models.CharField(
                max_length=64, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
