# Generated by Django 4.1.4 on 2023-01-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nhl", "0002_alter_nhlpreds_date_alter_nhlpreds_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="nhlpreds",
            name="blah",
            field=models.CharField(default="blah", max_length=64, verbose_name="blah"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nhlpreds",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
