# Generated by Django 4.1.4 on 2023-01-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nhl", "0003_nhlpreds_blah_alter_nhlpreds_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nhlpreds",
            name="blah",
        ),
    ]
