# Generated by Django 4.1.4 on 2023-01-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HitterPreds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("pa", models.FloatField(verbose_name="pa_pred")),
                ("runs", models.FloatField(verbose_name="r")),
                ("homerun", models.FloatField(verbose_name="hr")),
                ("rbi", models.FloatField(verbose_name="rbi")),
                ("sb", models.FloatField(verbose_name="sb")),
                ("obp", models.FloatField(verbose_name="obp")),
                ("value", models.FloatField(verbose_name="value")),
            ],
        ),
        migrations.CreateModel(
            name="PitcherPreds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("wins", models.FloatField(verbose_name="W")),
                ("so", models.FloatField(verbose_name="SO")),
                ("era", models.FloatField(verbose_name="ERA")),
                ("whip", models.FloatField(verbose_name="WHIP")),
                ("svh", models.FloatField(verbose_name="SVH")),
            ],
        ),
    ]
